#!/usr/bin/env python3

import nmap
import argparse
from threading import Thread

def scan(ip, port):
    scanner = nmap.PortScanner()
    scanner.scan(ip, port)
    print(ip, port, scanner[ip]['tcp'][int(port)]['state'])

def main():
    parser = argparse.ArgumentParser(description="A port scanner using nmap")
    parser.add_argument("ip", type=str, help="target ip")
    parser.add_argument("-p", "--port", metavar="port", type=int, help="a list of ports to scan", nargs="+", default=range(1024))
    args = parser.parse_args()
    ip, ports = args.ip, args.port
    for port in ports:
        t = Thread(target=scan, args=(ip, str(port)))
        t.start()

if __name__ == '__main__':
    main()
