#!/usr/bin/env python3

import argparse
from PyPDF2 import PdfFileReader

def printMeta(fileName):
    pdfFile = PdfFileReader(open(fileName, 'rb'))
    metadata = pdfFile.getDocumentInfo()
    print("PDF MetaData For:", fileName)
    for item in metadata:
        print(item, metadata[item])

def main():
    parser = argparse.ArgumentParser(description='get pdf metadata')
    parser.add_argument('file', type=str, help='path to the pdf file')
    args = parser.parse_args()
    fileName = args.file
    printMeta(fileName)

if __name__ == '__main__':
    main()
