#!/usr/bin/env python3

import argparse
import socket

def scan(host, port):
    socket.setdefaulttimeout(1)
    try:
        connSkt = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        connSkt.connect((host, port))
        print(port, "tcp open")
        connSkt.close()
    except:
        print(port, "tcp closed")

def main():
    parser = argparse.ArgumentParser(description="A port scanner")
    parser.add_argument("host", type=str, help="target host")
    parser.add_argument("port", type=int, help="target port")
    args = parser.parse_args()
    host, port = args.host, args.port
    scan(host, port)

if __name__ == '__main__':
    main()
