#!/usr/bin/env python

import socket

HOST = '0.0.0.0'
PORT = 5555

s = socket.socket()
s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
s.bind((HOST, PORT))
s.listen(1)
print(f'Listening as {HOST}:{PORT}')

client_s, client_addr = s.accept()
print(f'client connected {client_addr}')
client_s.send('welcome'.encode())

while True:
    cmd = input('>>> ')
    client_s.send(cmd.encode())

    if cmd.lower() == 'quit':
        break

    result = client_s.recv(1024).decode()
    print(result)

client_s.close()
s.close()
