#!/usr/bin/env python3

import zipfile
from threading import Thread
import argparse

parser = argparse.ArgumentParser(description='crack password protected zip file')
parser.add_argument('file', metavar='file', type=str, help='path to the archive')
parser.add_argument('dictionary', metavar='dictionary', type=str, help='path to the dictionary')
args = parser.parse_args()

def extractFile(zFile, password):
    try:
        zFile.extractall(pwd=bytes(password, 'utf-8'))
        print("Password : ", password)
    except:
        pass

def main():
    zFile = zipfile.ZipFile(args.file)
    passFile = open(args.dictionary)
    for line in passFile.readlines():
        password = line.strip('\n')
        t = Thread(target=extractFile, args=(zFile, password))
        t.start()

if __name__ == '__main__':
    main()
