#!/usr/bin/env python

import socket

HOST = ''
PORT = 50007

client = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
client.connect((HOST, PORT))
client.sendall(b'Hello, world!')
data = client.recv(1024)
print("Received", data.decode())
