#!/usr/bin/env python

import socket

HOST = ''
PORT = 50007

server = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
server.bind((HOST, PORT))
server.listen(1)

while True:
    conn, addr = server.accept()
    print(f'Accepted connection from {addr[0]}:{addr[1]}')
    data = conn.recv(1024)
    print("Received", data.decode())
    conn.sendall(b'ACK!')
