#!/usr/bin/env python

import socket
import threading

HOST = ''
PORT = 50007

server = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
server.bind((HOST, PORT))
server.listen(5)

print(f"Listening on {HOST}:{PORT}")

def handle_client(client):
    data = client.recv(1024)
    print("Received:", data.decode())
    client.sendall(b'ACK!')
    client.close()

while True:
    conn, addr = server.accept()
    print(f'Accepted connection from {addr[0]}:{addr[1]}')

    client_handler = threading.Thread(target=handle_client, args=(conn,))
    client_handler.start()
